spring:
  profiles:
    active: local

---
spring:  
  data:
    mongodb:
      #necessary param authSource
      uri: mongodb://admin:admin@127.0.0.1:27017/customers?authSource=admin
#      host: "localhost"
#      port: 27017
#      database: "customers"
#      username: "admin"
#      password: "admin"